version: '3.2'

services:

    qemu-test:
        image: docker-qemu-vm
        restart: on-failure
        container_name: qemu_test
        network_mode: host
        cap_add:
            - NET_ADMIN
        environment:
            - "QEMU_CPU=4"
            - "QEMU_MEM=4G"
            - "QEMU_BRIDGE=br0"
            - "QEMU_DISKS=/root.qcow2|4G"
            - "QEMU_CDROM=/ubuntu-server-amd64.iso"
            - "QEMU_MACADDR=96:CC:C2:20:4A:B2"
            - "QEMU_VNC_IDX=0"
            - "QEMU_EFI_NVRAM=/nvram"
            - "QEMU_QMP=127.0.0.1:7000"
        devices:
            - "/dev/kvm:/dev/kvm"
            - "/dev/net/tun:/dev/net/tun"
        volumes:
            - type: bind
              source: ./ubuntu-server-amd64.iso
              target: /ubuntu-server-amd64.iso
            - type: bind
              source: ./test-root.qcow2
              target: /root.qcow2
            - type: bind
              source: ./test-nvram
              target: /nvram
